<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRImFOg0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRImFOg0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRImFOg0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRImFOg0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRImFOg0\App_KernelDevDebugContainer([
    'container.build_hash' => 'RImFOg0',
    'container.build_id' => 'af76fda4',
    'container.build_time' => 1684823954,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRImFOg0');
